Indoor
3D printing[1]
Acrobatics
Acting[2]
Amateur radio[3]
Animation
Aquascaping
Baking
Baton twirling[4]
Beatboxing
Board/tabletop games[5]
Book restoration
Cabaret
Calligraphy[6]
Candle making[7]
Coffee roasting
Collecting
Coloring[8]
Computer programming[9]
Cooking[10]
Cosplaying[11]
Couponing[12]
Creative writing[13]
Crocheting[14]
Cross-stitch
Crossword puzzles
Cryptography[15]
Dance[16]
Digital arts[17]
Do it yourself[18]
Drama[19]
Drawing[20]
Electronics[21]
Embroidery[22]
Fantasy sports
Fashion
Fishkeeping
Flower arranging[23]
Foreign language learning[24]
Gaming (tabletop games and role-playing games)[25]
Genealogy[26]
Glassblowing[27]
Graphic design
Gunsmithing
Herp keeping
Homebrewing[28]
Hydroponics[29]
Ice skating[30]
Jewelry making[31]
Jigsaw puzzles[32]
Juggling[33]
Knife making
Knitting[34]
Kombucha brewing
Lace making[35]
Lapidary[36]
Leather crafting
Lego building[37]
Listening to music[38]
Machining[39]
Macrame[40]
Magic[41]
Metalworking
Model building[42]
Model engineering
Needlepoint
Origami[43]
Painting[44]
Philately
Photography
Playing musical instruments[45]
Poi
Pottery[46]
Puzzles[47]
Quilling
Quilting[48]
Reading[49]
Robot combat
Scrapbooking[50]
Sculpting[51]
Sewing[52]
Singing[53]
Sketching[20]
Soapmaking[54]
Stand-up comedy[55]
Table tennis[56]
Taxidermy[57]
Video game developing
Video gaming[58]
Video editing
Watching movies[59]
Watching television
Whittling
Wood carving[60]
Woodworking[61]
Worldbuilding[62]
Writing[63]
Yo-yoing[64]
Yoga[65]

Outdoor
Air sports[66]
Archery[67]
Astronomy[68]
BASE jumping[69]
Baseball[70]
Basketball[71]
Beekeeping[72]
Bird watching[73]
Blacksmithing
BMX[74]
Board sports[75]
Bodybuilding[76]
Brazilian jiu-jitsu[77]
Camping
Canoeing
Canyoning
Dowsing[78]
Driving[79]
Fishing[80]
Flag football[81]
Flying[82]
Flying disc
Foraging[83]
Freestyle football[84]
Gardening[85]
Geocaching[86]
Ghost hunting[87]
Graffiti[88]
Handball[89]
High-power rocketry
Hiking[90]
Hooping[91]
Horseback riding
Hunting[92]
Inline skating[93]
Jogging[94]
Kayaking[95]
Kite flying[96]
Kitesurfing[97]
LARPing[98]
Letterboxing[99]
Longboarding
Martial arts
Metal detecting[100]
Motor sports[101]
Mountain biking[102]
Mountaineering[103]
Mushroom hunting/mycology[104]
Netball[105]
Nordic skating[106]
Orienteering[107]
Paintball[108]
Parkour[109]
Photography[110]
Polo[111]
Powerlifting
Rafting[112]
Rappelling[113]
Road biking
Rock climbing[103]
Roller skating[114]
Rugby[115]
Running[94]
Sailing[116]
Sand art[117]
Scouting
Scuba diving[118]
Sculling or rowing[119]
Shooting[120]
Shopping[121]
Skateboarding[122]
Skiing[123]
Skimboarding[124]
Skydiving[125]
Slacklining[126]
Snowboarding[123]
Stone skipping[127]
Sun bathing
Surfing[128]
Swimming[129]
Taekwondo[130]
Tai chi[131]
Topiary
Travel
Urban exploration[132]
Vacation
Vehicle restoration[133]
Walking
Water sports[134]

Collection
Action figure
Antiquing[135]
Art collecting[136]
Book collecting[137]
Card collecting[138]
Coin collecting[139]
Comic book collecting[140]
Deltiology (postcard collecting)[141]
Die-cast toy
Dolls
Element collecting[142]
Knife collecting
Movie and movie memorabilia collecting[143]
Perfume
Phillumeny
Rail transport modelling
Record collecting[144]
Shoes
Stamp collecting[145]
Video game collecting[146]
Vintage cars[147]
Outdoors
Antiquities[148]
Auto audiophilia[149]
Flower collecting and pressing[150]
Fossil hunting[151]
Insect collecting[152]
Magnet fishing
Metal detecting[153]
Mineral collecting[154]
Rock balancing[155]
Sea glass collecting[156]
Seashell collecting[157]
Stone collecting[158]

Competitive
Animal fancy[159]
Badminton[160]
Baton twirling[161]
Billiards[162]
Bowling[163]
Boxing[164]
Bridge[165]
Cheerleading[166]
Chess[167]
Color guard[168]
Curling[169]
Dancing[170]
Darts[171]
Debate[172]
Eating
ESports
Fencing[173]
Go[174]
Gymnastics[175]
Ice skating[176]
Kabaddi[177]
Laser tag[178]
Longboarding
Mahjong[179]
Marbles[180]
Martial arts[181]
Poker[182]
Shogi
Slot car racing[183]
Speedcubing
Sport stacking
Table football[184]
Volleyball[185]
Weightlifting[186]
Wrestling
Airsoft[187]
American football[188]
Archery[67]
Association football[189]
Astrology[190]
Australian rules football[191]
Auto racing[192]
Baseball[193]
Beach volleyball[194]
Breakdancing[195]
Climbing[103]
Cricket[196]
Cycling[197]
Disc golf[198]
Dog sport[199]
Equestrianism[200]
Exhibition drill[201]
Field hockey[202]
Figure skating[30]
Fishing[203]
Footbag[204]
Golfing[205]
Handball[89]
Horseback riding
Ice hockey[206]
Judo[207]
Jukskei[208]
Kart racing[209]
Knife throwing
Lacrosse
Longboarding
Marching band
Model aircraft[210]
Racquetball[211]
Radio-controlled car racing[212]
Roller derby[213]
Rugby league football[214]
Sculling or rowing
Shooting sport[215]
Skateboarding[216]
Speed skating[30]
Squash[211]
Surfing[128]
Swimming[129]
Table tennis[56]
Tennis[217]
Tennis polo
Tether car
Tour skating[106]
Triathlon[218]
Ultimate frisbee[219]
Volleyball[194]
Water polo

Observation
Fishkeeping
Learning
Meditation
Microscopy[220]
Reading[221]
Shortwave listening[222]
Videophilia[223]
Aircraft spotting[224]
Amateur astronomy[68]
Birdwatching[73]
Bus spotting[225]
Geocaching[86]
Gongoozling[226]
Herping
Hiking/backpacking
Meteorology
Photography
Satellite watching
Trainspotting
Traveling
Whale watching